'use client';

import { useArticles } from "@/hooks/useArticles";
import { ArticleList } from "@/components/ArticleList";
import { useState, useEffect } from "react";
import { AppHeader } from "@/components/AppHeader";
import { clsx } from "clsx";
import { Sparkles, Loader2, X } from 'lucide-react';
import { AIService } from "@/lib/ai-service";
import { useSettingsStore } from "@/store/settingsStore";

function BriefingCard() {
  const { openaiApiKey } = useSettingsStore();
  const [briefing, setBriefing] = useState<string | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [isVisible, setIsVisible] = useState(true);

  useEffect(() => {
    // Check if we have a briefing for today
    AIService.getTodayBriefing().then(setBriefing);
  }, []);

  if (!openaiApiKey || !isVisible) return null;

  const handleGenerate = async () => {
    setLoading(true);
    setError(null);
    try {
      const text = await AIService.generateDailyBriefing();
      setBriefing(text);
    } catch (e: any) {
      setError(e.message);
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="mx-4 sm:mx-6 mt-4 mb-2">
      <div className="bg-gradient-to-br from-indigo-50 to-purple-50 dark:from-indigo-950/30 dark:to-purple-900/30 rounded-xl border border-indigo-100 dark:border-indigo-800/50 p-4 relative overflow-hidden">
        
        <div className="flex items-center justify-between mb-3">
          <div className="flex items-center gap-2 text-indigo-900 dark:text-indigo-200 font-semibold">
            <Sparkles size={18} className="text-indigo-600 dark:text-indigo-400" />
            Daily Briefing
          </div>
          <button onClick={() => setIsVisible(false)} className="text-indigo-400 hover:text-indigo-600 dark:hover:text-indigo-200">
            <X size={16} />
          </button>
        </div>

        {briefing ? (
          <div className="prose prose-sm prose-indigo dark:prose-invert max-w-none">
            <div className="whitespace-pre-line text-zinc-700 dark:text-zinc-300">
              {briefing}
            </div>
            <p className="text-xs text-indigo-400 mt-4 font-medium">Generated by AI based on your unread feeds.</p>
          </div>
        ) : (
          <div className="flex flex-col sm:flex-row items-start sm:items-center gap-4">
            <p className="text-sm text-indigo-800 dark:text-indigo-300 flex-1">
              Catch up quickly with an AI-generated summary of your top unread stories from the last 24 hours.
            </p>
            <button
              onClick={handleGenerate}
              disabled={loading}
              className="bg-indigo-600 hover:bg-indigo-700 text-white px-4 py-2 rounded-lg text-sm font-medium transition-colors flex items-center gap-2 shadow-sm shrink-0"
            >
              {loading ? <Loader2 size={16} className="animate-spin" /> : <Sparkles size={16} />}
              {loading ? 'Generating...' : 'Generate Briefing'}
            </button>
          </div>
        )}
        
        {error && (
            <div className="mt-3 text-xs text-red-500 bg-red-50 dark:bg-red-900/20 p-2 rounded border border-red-100 dark:border-red-800">
                {error}
            </div>
        )}
      </div>
    </div>
  );
}

export default function HomePage() {
  const [view, setView] = useState('today');
  const articles = useArticles(view);
  const [searchQuery, setSearchQuery] = useState('');

  // Filter articles client-side based on search query
  const filteredArticles = (articles || []).filter(article => {
    if (!searchQuery) return true;
    const q = searchQuery.toLowerCase();
    return (
      article.title.toLowerCase().includes(q) ||
      article.summary?.toLowerCase().includes(q) ||
      (article.contentHTML && article.contentHTML.toLowerCase().includes(q))
    );
  });

  return (
    <div className="h-screen flex flex-col bg-zinc-50 dark:bg-zinc-950">
      <AppHeader
        showSearch={true}
        searchValue={searchQuery}
        onSearchChange={setSearchQuery}
      />

      {/* Filter Tabs */}
      <div className="px-4 sm:px-6 py-3 border-b border-zinc-200/50 dark:border-zinc-800/50 bg-white/50 dark:bg-zinc-950/50 backdrop-blur-sm sticky top-14 z-20">
        <div className="flex gap-2 overflow-x-auto scrollbar-hide">
          {['today', 'last24h', 'week', 'all'].map(v => (
            <button
              key={v}
              onClick={() => setView(v)}
              className={clsx(
                "px-3 py-1.5 text-xs font-medium rounded-full border transition-all capitalize whitespace-nowrap shrink-0",
                view === v
                  ? "bg-zinc-900 dark:bg-zinc-100 text-white dark:text-zinc-900 border-transparent"
                  : "bg-transparent border-zinc-200 dark:border-zinc-800 text-zinc-600 dark:text-zinc-400 hover:border-zinc-300 dark:hover:border-zinc-700"
              )}
            >
              {v === 'last24h' ? 'Last 24h' : v}
            </button>
          ))}
        </div>
      </div>

      {/* Briefing Card (Only on Today view) */}
      {view === 'today' && <BriefingCard />}

      {/* Content Area */}
      <div className="flex-1 overflow-hidden">
        {filteredArticles ? (
          <ArticleList articles={filteredArticles} />
        ) : (
          <div className="flex items-center justify-center h-full">
            <div className="animate-pulse text-zinc-400">Loading...</div>
          </div>
        )}
      </div>
    </div>
  );
}
